version = 1

[server]
bind_addr = "127.0.0.1"
port = 8080

[webapp]
base_url = https://thephish.example.com # URL used to access thephish
# target URLs for the navbar links
thehive_url = "https://link-to-thehive/"
cortex_url = "https://link-to-cortex/"
misp_url = "https://link-to-misp/"

[redis]
# Application data (logical database 0).
url = "redis://127.0.0.1:6379/0"
key_prefix = "thephish"
celery_broker_url = "redis://127.0.0.1:6379/1"
celery_result_backend_url = "redis://127.0.0.1:6379/2"

[analysis]
# analysis settings
retention_days = 7 # after how many days should thephish drop finished analyses? (cases will stay available in thehive)
decode_o365_safelinks = true # Decode outlook safelinks and add the found url as observable
follow_url_redirects = true # Follow HTTP redirects of found urls and add all urls in the redirect trace as observables
analyzer_prefix_blacklist = ["UnshortenLink", "MSDefenderOffice365_SafeLinksDecoder_json"] # List of analyzer name prefixes that will never be run

[imap]
# imap configuration for accessing mail inbox
host = "imap.gmail.com"
port = 993
tls_mode = "tls" # must be 'tls', 'starttls' or 'none'
tls_verify = true # disable certificate validation
user = "example@gmail.com"
password = "passwort.213"
folder = "inbox"
max_message_size_mb = 25 # max message size in Mebibyte
email_list_amount = 20 # how much emails to list when retrieving emails

[thehive]
# thehive api settings
url = "http://thehive:9000"
apikey = "generated_api_key"
tls_verify = true # disable certificate validation
cortex_id = "cortex" # Cortex server identifier configured in thehive
misp_id = "MISP" # MISP server identifier configured in TheHive

[case]
# TheHive case settings
tlp = 2
pap = 2
tags = ["email", "ThePhish"]
