version = 1

[server]
bind_addr = "127.0.0.1"
port = 8080

[webapp]
# target URLs for the navbar links
thehive_url = "https://link-to-thehive/"
cortex_url = "https://link-to-cortex/"
misp_url = "https://link-to-misp/"

[imap]
# imap configuration for accessing mail inbox
host = "imap.gmail.com"
por = "993"
tls_mode = "tls" # must be 'tls', 'starttls' or 'none'
tls_insecure = "no" # disable certificate validation
user = "example@gmail.com"
password = "passwort.213"
folder = "inbox"

[thehive]
# thehive api settings
url = "http://thehive:9000"
apikey = "generated_api_key"
tls_insecure = "no" # disable certificate validation

[cortex]
# cortex api settings
url = "http://cortex:9001"
apikey = "generated_api_key"
id = "cortex" # Cortex server identifier configured in thehive
tls_insecure = "no" # disable certificate validation

[misp]
id = "MISP" # MISP server identifier configured in TheHive

[case]
# TheHive case settings
tlp = 2
pap = 2
tags = ["email", "ThePhish"]
